### ISSUE TITLE
[Question]: How Inject dependencies in the DoneCallback function?

### ISSUE THREAD

**Issue by cdiaz** [fwoelffel/nest-bull#1]
The typical cases for process functions include database operations and use of another components.
What is the best way to call functions from the nest components from here?
How do use Dependency Injector on this case?
Example:
```js
const BtcPriceProcessor = async (job) => {
 return await this.btcPriceService.fetch('USD')
  .then(result => Promise.resolve(result);)
  .catch(err=> Promise.reject(err) 
}
export { BtcPriceProcessor }
```
See to full code in [this repository](https://github.com/cdiaz/nest-job-queue)

**Comment by cdiaz** [comment]
have managed to obtain the instance of my component through the [Execution Context](https://docs.nestjs.com/execution-context):

```js
import { NestFactory } from '@nestjs/core';
import { BtcPriceModule } from '../../btcprice/btcprice.module';
import { BtcPriceService } from '../../btcprice/btcprice.service';

const BtcPriceProcessor = async (job) => {
  
  const context = await NestFactory.createApplicationContext(BtcPriceModule);
  const btcPriceService = context.get(BtcPriceService);

  return await btcPriceService.fetch(job.data.currency)
    .then(data=> Promise.resolve(data))
    .catch(err=> Promise.reject(err))
}

export { BtcPriceProcessor }
```

This solution works fine for me, but I want to know if it is the best way to do it

**Comment by fwoelffel** [comment]
Hi @cdiaz 

At the moment I can't think of a better way to get access to the components. Your solution looks neat; I might add it as an example in the README :wink: 

I'll leave this issue opened for a while in case someone comes with another implementation.

**Comment by cdiaz** [comment]
Hi @fwoelffel thanks for your reply.

I found another implementation to solve it, declaring the application as a global variable within the namespace, so the context of the execution was not initialized in each iteration of the cron job.

I'm talking about this in @nestjs/nest/issues/544 to known more opinions.

**Comment by fwoelffel** [comment]
This has been answered there https://github.com/nestjs/nest/issues/544#event-1586854526 :wink:
