### ISSUE TITLE
Dependencies cannot be resolved when using forRootAsync

### ISSUE THREAD

**Issue by joshuajung** [fwoelffel/nest-bull#10]
I have implemented nest-bull in a fully working way by using `BullModule.forRoot` like this:
```
@Injectable()
export class SlackAnnounceRankingProcessor {
  constructor(@InjectQueue('slack-announce') private readonly queue: Queue) {}
}

@Module({
  imports: [
    ConfigModule,
    BullModule.forRoot({
      name: 'slack-announce',
      options: {
        redis: {
          port: 6379,
        },
      },
    }),
  ],
  providers: [SlackAnnounceRankingProcessor],
  controllers: [],
})
export class SlackModule {}
```

 I am now trying to switch over to `forRootAsync` to import a custom ConfigModule. My classes - simplified - are now as follows:

```
@Injectable()
export class SlackAnnounceRankingProcessor {
  constructor(@InjectQueue('slack-announce') private readonly queue: Queue) {}
}

@Module({
  imports: [
    ConfigModule,
    BullModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: (configService: ConfigService) => ({
        name: 'slack-announce',
        options: {
          redis: {
            port: 6379,
          },
        },
      }),
      inject: [ConfigService],
    }),
  ],
  providers: [SlackAnnounceRankingProcessor],
  controllers: [],
})
export class SlackModule {}
```

Unfortunately, this yields the following NestJS error:
```
[Nest] 57472   - 2019-3-2 17:51:48   [ExceptionHandler] Nest can't resolve dependencies of the SlackAnnounceRankingProcessor (?). Please make sure that the argument at index [0] is available in the SlackModule context. +15ms
Error: Nest can't resolve dependencies of the SlackAnnounceRankingProcessor (?). Please make sure that the argument at index [0] is available in the SlackModule context.
    at Injector.lookupComponentInExports (/Users/jaj/Repositories/mausauel-server/node_modules/@nestjs/core/injector/injector.js:144:19)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
    at Function.Module.runMain (module.js:695:11)
    at Object.<anonymous> (/Users/jaj/Repositories/mausauel-server/node_modules/ts-node/src/bin.ts:157:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

As I'm rather new to NestJS this may entirely be my fault, but maybe someone would have the time to double check and point me into the right direction? That would be awesome. Thanks a lot!

**Comment by mayorandrew** [comment]
Based on https://github.com/fwoelffel/nest-bull/blob/master/lib/bull.providers.ts#L39 it looks like that you should have `name` property defined outside of the `useFactory`, like this:
```
@Module({
  imports: [
    ConfigModule,
    BullModule.forRootAsync({
      imports: [ConfigModule],
      name: 'slack-announce',
      useFactory: (configService: ConfigService) => ({
        options: {
          redis: {
            port: 6379,
          },
        },
      }),
      inject: [ConfigService],
    }),
  ],
  providers: [SlackAnnounceRankingProcessor],
  controllers: [],
})
export class SlackModule {}
```

This works. It doesn't seem quite right though...

**Comment by fwoelffel** [comment]
@joshuajung Sorry I didn't have quite the time to investigate on this issue yet. Could you confirm that @mayorandrew's answer is fixing your issue?

@mayorandrew yup, you're right, I don't know why I implemented this non-sense. Sorry for that, I'll try to deprecate this and provide a non-breaking solution to this. Thanks for taking some of your time to have a look on this.

**Comment by joshuajung** [comment]
@fwoelffel Happy to confirm this did the trick!
@mayorandrew Thanks a lot for your effort! I would have never found that myself.

**Comment by fwoelffel** [comment]
Awesome, thanks for your feedback. I feel like I should add a `forRootAsync` example in the README.
I'm closing this.

**Comment by fwoelffel** [comment]
Hi @joshuajung :wave:
I've look into the code and I'm affraid it won't be possible to define the queue name from the `useFactory`. If you take a look at https://github.com/fwoelffel/nest-bull/blob/master/lib/bull.providers.ts#L46 (or https://github.com/fwoelffel/nest-bull/blob/13-async-array-configuration/lib/bull.providers.ts#L45 which will soon be merged into master) you can see by your self that I need the queue name to build the injection token. Thus, I can't wait for the result of the `useFactory` function.
If you have an idea on how to do this, feel free to submit a PR 🙂

**Comment by joshuajung** [comment]
Hey @fwoelffel, Thanks a lot for taking the time and looking into it! Now that I know that `name` is defined outside `useFactory`, that's perfectly fine for me. Thanks again!

**Comment by JVMartin** [comment]
Just ran into this now in 2020.

The docs do not detail this at all:
https://docs.nestjs.com/techniques/queues

Would someone with the appropriate power be able to update the docs to include a `name` property in the proper location in the `.registerQueueAsync` section? This would have taken me many hours to figure out without this thread.

**Comment by kamilmysliwiec** [comment]
@JVMartin I've just pushed an update to the docs. Thanks!

**Comment by investeusa** [comment]
> @JVMartin Acabei de enviar uma atualização aos documentos. Obrigado!

Did you test this? The documentation is not clear to those who are starting.

I have the same problem.

`
**queues.config.module.ts**
@Module({
    imports: [
        BullModule.forRootAsync({
            imports: [ConfigModule],
            inject: [ConfigService],
            useFactory: async (configService: ConfigService) => ({
                redis: {
                    host: configService.get('REDIS_HOST'),
                    port: configService.get('REDIS_PORT'),
                },
            }),
        }),
        QuotesQueueModule
    ]
})
export class QueuesModule {}
`

`
**queues.service.ts**

@Injectable()
class BullConfigService implements BullOptionsFactory {
  createBullOptions(): BullModuleOptions {
    return {
      redis: {
        host: 'localhost',
        port: 6379,
      },
    };
  }
}

`

`
**error:**
(node:261) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 0.0.0.0:6379
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)
(node:261) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
`

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
