### ISSUE TITLE
Job failed without handlers

### ISSUE THREAD

**Issue by adikaladik** [fwoelffel/nest-bull#103]
Basically didn't know where to put the issue here or in the original bull repo. But here below is the description: 
  I have 2 projects. In the first one I have job producer:
```ts
import { Job, Queue } from 'bull';
import { Logger } from '@nestjs/common';
import { InjectQueue } from 'nest-bull';

export class ProcessIntegrationsQueue {
  private readonly logger = new Logger('ProcessIntegrationsQueue');

  constructor(@InjectQueue('integration2') readonly queue: Queue) {
    this.logger.log('Start adding jobs to queue...');
    let i = 1;
    setInterval(async () => {
      await this.addJob(i);
      i++;
    }, 50000);
  }

  async addJob(id: number) {
    const job: Job = await this.queue.add('integration', `user: ${id}`, { backoff: 50, attempts: 10 });
    this.logger.log(`new job added with id ${job.id}`);
  }
}
```
In the second one - consumer: 
```ts
import {
  Queue,
  QueueProcess,
  OnQueueActive,
  OnQueueEvent,
  BullQueueEvents,
} from 'nest-bull';
import { Job, DoneCallback } from 'bull';
import { Logger } from '@nestjs/common';

@Queue({name: 'integration2'})
export class JobProcessor {
  private readonly logger = new Logger('Job executor');

  @QueueProcess({ name: 'integration' })
  processTwice(job: Job<number>) {
    this.logger.log(` process handler 1 works: ${job.data}`);
    return job.data;
  }
  
  @OnQueueActive()
  onActive(job: Job) {
    this.logger.log(
      `Processing job ${job.id} of type ${job.name} with data ${job.data}...`,
    );
  }

  @OnQueueEvent(BullQueueEvents.COMPLETED)
  onCompleted(job: Job) {
    this.logger.log(
      `Completed job ${job.id} of type ${job.name} with result ${
        job.returnvalue
        }`,
    );
  }
}
```
Consumer starts in one minute after producer and all jobs produced on that minute are with error 

> ["Error: Missing process handler for job type integration\n    at Queue.processJob

Is there any way to wait for those jobs until the consumer connects to the queue? 

Moreover, If I even run producer later than consumer the first jobs fail with the error I mentioned above..

**Comment by fwoelffel** [comment]
I tried to adapt my sample application to your usecase by adding a name to the queue but I can't reproduce. What version of `nest-bull` are you using? Could you share a repository?

**Comment by adikaladik** [comment]
@fwoelffel, unfortunately, can't share, repo is not public...
version is  "nest-bull": "^0.8.0",

**Comment by adikaladik** [comment]
that is interesting when the first job in queue executes on redis I see the following [(https://ibb.co/xLQZ9Sd)]
the job seems to be completed, but the inside error has occurred

**Comment by fwoelffel** [comment]
Can you share your `AppModule`? Could you try to trigger your job somewhere else than in a `constructor` or a `setTimeOut`?

**Comment by adikaladik** [comment]
Module from the first progect which adds jobs to queue 
`import { BullModule, InjectQueue } from 'nest-bull';
import { Job, DoneCallback, Queue } from 'bull';
import { Module } from '@nestjs/common';
import { ProcessIntegrationsQueue } from '../cron/AddUsersToQueue';

@Module({
  imports: [
    BullModule.forRoot({
      name: 'integration2',
      options: {
        redis: {
          port: 6379,
          host: '127.0.0.1',
          //password: '4m538Vo8q6ohv8Xzivby8hUbFaipqYK3',
        },
      },
      processors: [
        (job: Job, done: DoneCallback) => {
          done(null, job.data);
        },
      ],
    }),
  ],
  providers: [ProcessIntegrationsQueue],
})
export class QueueModule {}
`

Module from 2nd which consumes jobs:

**Comment by adikaladik** [comment]
Module from 1st module which produces jobs:
```
import { BullModule, InjectQueue } from 'nest-bull';
import { Job, DoneCallback, Queue } from 'bull';
import { Module } from '@nestjs/common';
import { ProcessIntegrationsQueue } from '../cron/AddUsersToQueue';

@Module({
  imports: [
    BullModule.forRoot({
      name: 'integration2',
      options: {
        redis: {
          port: 6379,
          host: '127.0.0.1',
          //password: '4m538Vo8q6ohv8Xzivby8hUbFaipqYK3',
        },
      },
      processors: [
        (job: Job, done: DoneCallback) => {
          done(null, job.data);
        },
      ],
    }),
  ],
  providers: [ProcessIntegrationsQueue],
})
export class QueueModule {}
```
Module from 2nd project which consumes jobs:
import { BullModule } from 'nest-bull';
import { Job, DoneCallback } from 'bull';
import { Module } from '@nestjs/common';
import { JobProcessor } from '../queue/JobProcessor';

```
@Module({
  imports: [
    BullModule.forRoot({
      name: 'integration2',
      options: {
        redis: {
          port: 6379,
          host: '127.0.0.1',
          // password: '4m538Vo8q6ohv8Xzivby8hUbFaipqYK3',
        },
      },
    }),
  ],
  providers: [JobProcessor],
})
export class QueueModule {}
```
Tried to add job as described in doc with API. Situation is the same. 
I add job to queue then ran 2nd project with consumer - in redis this job is failed and consumer does not try to work with that. 
May this problem related to Redis version? @fwoelffel

**Comment by fwoelffel** [comment]
It looks like you're injecting two different queue in your modules. Try to move your `BullModule.forRoot` call higher in your DI tree. Have a look at https://docs.nestjs.com/modules

**Comment by fwoelffel** [comment]
This looks related to https://github.com/OptimalBits/bull/issues/625

**Comment by adikaladik** [comment]
Found an issue. In the project which produces jobs, I removed this piece of code from BullModule.forRoot call and it started working properly.
```
 processors: [
        (job: Job, done: DoneCallback) => {
          done(null, job.data);
        },
      ],
```
@fwoelffel thank you for support!

**Comment by fwoelffel** [comment]
It's nice to hear that we solved your issue :slightly_smiling_face:
