### ISSUE TITLE
Nest cant resolve dependencies on latest NestJS

### ISSUE THREAD

**Issue by maksimkurb** [fwoelffel/nest-bull#110]
I import `BullModule.forRoot` in AppModule and then `@InjectQueue` in AnotherModule (which depends on AppModule),
NestJS failing with error:
`
Nest can't resolve dependencies of the AnotherController (?). Please make sure that the argument at index [0] is available in the AnotherModule context.
`

Error appears on latest NestJS version, 6.3.1
May be [this commit](https://github.com/nestjs/nest/commit/f210ebca2fddecef6b235547498b46fe76b3b9e5) is responsible for that.

[Made a sample](https://github.com/maksimkurb/nest-bull/tree/bug-nest-cant-resolve-sample/sample)

**Comment by fwoelffel** [comment]
Hi @maksimkurb and thanks for reporting.
Was your sample working before NestJS 6.3.1?

**Comment by maksimkurb** [comment]
Sorry, did an example in a hurry, so I made some mistakes. Now I updated it and this is correct, that it is not working on NestJS 6.3.1, but working fine on NestJS 6.3.0

**Comment by maksimkurb** [comment]
@fwoelffel, I got it! We should add `@Global()` decorator to BullModule so we can use queue in other modules. Another option is to create method `BullModule.forFeature()` like in TypeORM module, but this will be a breaking change.
I will create a pull request in a couple of minutes

**Comment by fwoelffel** [comment]
I think having a `SharedModule` that exports your queue, and that is imported in whichever modules where you need the queue to be injected, could solve your issue.
Would you try that? I'd prefer not to increase the code complexity as long as this can be avoided.

**Comment by fwoelffel** [comment]
I really don't like the `Global` solution :wink:

**Comment by maksimkurb** [comment]
SharedModule is also the solution, but then `forRoot` method name is confusing. Better to be called `register` like in `HttpModule`

**Comment by fwoelffel** [comment]
I understand that. I think the real issue here is the lack of documentation/examples.

Anyway, should we close this issue?

**Comment by maksimkurb** [comment]
Yes, I think so. With #116 it will be better solution.

Leaving a sample of shared module for anyone who is interested:
```ts
const QueueModule = BullModule.forRoot({ // BullModule.register
  name: 'test',
});

@Module({
  imports: [QueueModule],
  exports: [QueueModule],
})
export class SharedModule {}
```

**Comment by ofebles** [comment]
I need create sessions for handle queues of inline clients, when creating a new session, I need to create a new queue  with session name (dynamic) , but in nestjs docs you always know the queue name for registering and later inject it . How i can manage the dynamic creation of bull queues in nestjs?
