### ISSUE TITLE
NestJS v6

### ISSUE THREAD

**Issue by victordidenko** [fwoelffel/nest-bull#16]
Nest v6 got released half a month ago, and all deprecations (from 4 to 5 version) have been removed (https://docs.nestjs.com/migration-guide).
`components` are not supported in module declarations, there should be `providers` instead:
https://github.com/fwoelffel/nest-bull/blob/master/lib/bull.module.ts#L12
So Nest doesn't work will BullModule anymore
> Error: Nest cannot export a provider/module that is not a part of the currently processed module (BullModule). Please verify whether each exported unit is available in this particular context.

**Comment by victordidenko** [comment]
Ah, there is still pending PR #14 ...

**Comment by fwoelffel** [comment]
Closed by #14 thanks to @cappuc
