### ISSUE TITLE
Please add an example for using classes (with deps) as processors.

### ISSUE THREAD

**Issue by moltar** [fwoelffel/nest-bull#5]
I am not sure if this is even possible, but it'd be nice to be able to define processors as regular NestJS service classes, with dependencies and all. Is that even possible?

Thanks.

**Comment by fwoelffel** [comment]
Sure this is possible :slightly_smiling_face: 

You can inject Bull queues in your injectables :

```ts
import { Injectable, OnModuleInit } from '@nestjs/common';
import { DoneCallback, Job, Queue } from 'bull';
import { InjectQueue } from 'nest-bull';

@Injectable()
export class MyProcessor implements OnModuleInit {

  constructor (
    @InjectQueue('my_queue') private readonly queue: Queue
  ) {}


  onModuleInit() {
    this.queue.process((job: Job, done: DoneCallback) => {
      done(null, job.data);
    });
  }

}
```

Don't forget to provide your `MyProcessor` injectable.
I haven't tested this code so let me know if it works properly :wink:

**Comment by moltar** [comment]
Perfect, that works! Didn't know about `onModuleInit`.

Thank you!
