### ISSUE TITLE
Processor in separate process

### ISSUE THREAD

**Issue by iveselin** [fwoelffel/nest-bull#52]
#### Question
In Bull [docs](https://github.com/OptimalBits/bull#separate-processes), there is a way to execute jobs in separate processes, but I can't find a way to create such jobs within this module.
Am I missing something or it has not been implemented yet?

**Comment by fwoelffel** [comment]
Hi @iveselin 

This has not been implemented but I imagine this is not a big deal. However, I don't think you would be able to use any service in your processor if it is executed in a separate process.
Feel free to have a look on this an submit a PR.

**Comment by klerick** [comment]
@fwoelffel PR https://github.com/fwoelffel/nest-bull/pull/50 could add it. If create separate nest application with process decorator.

**Comment by cgarnier** [comment]
Hi @iveselin
I m looking for this feature too. Did you find a way to do it properly ?
I think it s possible to copy main.ts to worker.ts and remove app.listen. The worker should boostrap and the services should be available. But i dont know if it s possible to remove the useless of the app (controllers ) of the worker.
You can also do something similar with node cluster.

**Comment by fwoelffel** [comment]
I've done something similar not so long ago. I used a cluster in which the master created an app with the "normal" `AppModule` and the workers used a "lightweight" version of the `AppModule` (without controlers, etc.). What @cgarnier is describing could work perfectly but it wouldn't make use of the Bull feature to which @iveselin refers.
Maybe that's still an acceptable answer.

I'll also try to use the Bull feature, and document its usage with this module (I just have to find some time for this).

**Comment by cgarnier** [comment]
If you check the bull code, It s not 'real' processes anyway. They run the jobs in process.nextTick.

**Comment by fwoelffel** [comment]
Looks like an actual fork to me (https://github.com/OptimalBits/bull/blob/develop/lib/process/child-pool.js#L49). The easiest way to be sure would be to schedule a job writing its PID somewhere.

**Comment by fwoelffel** [comment]
I've had a quick look at this, and we can make this work :tada: 

Here a few lines of code that depict this feature in action.

```ts
// app.module.ts
import { Module, OnModuleInit } from '@nestjs/common';
import { AppController } from './app.controller';
import { BullModule } from '../../lib';
import { join } from 'path';

@Module({
  imports: [
    BullModule.forRoot({
      processors: [ join(__dirname, 'processor.ts') ]
    }) 
  ],
  controllers: [ AppController ] // I add jobs through this controller
})
export class AppModule implements OnModuleInit {
  onModuleInit() {
    console.log('MAIN ', process.pid);
  }
}
```
```ts
// processor.ts
import {Job, DoneCallback} from 'bull';

export default function(job: Job, cb: DoneCallback) {
  console.log('CHILD ', process.pid);
  cb(null, 'It works');
}
```
Log output:
```
[Nest] 15191   - 05/07/2019, 10:23 PM   [NestFactory] Starting Nest application...
[Nest] 15191   - 05/07/2019, 10:23 PM   [InstanceLoader] BullModule dependencies initialized +17ms
[Nest] 15191   - 05/07/2019, 10:23 PM   [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 15191   - 05/07/2019, 10:23 PM   [RoutesResolver] AppController {/}: +4ms
[Nest] 15191   - 05/07/2019, 10:23 PM   [RouterExplorer] Mapped {/, GET} route +0ms
MAIN  15191
[Nest] 15191   - 05/07/2019, 10:23 PM   [NestApplication] Nest application successfully started +3ms
[ ... ] // Then I add a job to the queue
CHILD  15222
```
As you can see, the PID is not the same for the Nest app and the processor function.

**Comment by fwoelffel** [comment]
Here is the currently possible types for the `processors` property :
```ts
export type BullQueueProcessor =
  | BullQueueProcessorCallback
  | BullQueueAdvancedProcessor;

export type BullQueueProcessorCallback = (
  job: Job,
  done?: DoneCallback,
) => void;

export interface BullQueueAdvancedProcessor {
  concurrency?: number;
  name?: string;
  callback: BullQueueProcessorCallback;
}
```

Here's my proposal:
```ts
export type BullQueueProcessor =
  | BullQueueProcessorCallback
  | BullQueueAdvancedProcessor
  | BullQueueSeparateProcessor
  | BullQueueAdvancedSeparateProcessor;

export type BullQueueSeparateProcessor = string;

export type BullQueueProcessorCallback = (
  job: Job,
  done?: DoneCallback,
) => void;

export interface BullQueueAdvancedProcessor {
  concurrency?: number;
  name?: string;
  callback: BullQueueProcessorCallback;
}

export interface BullQueueAdvancedSeparateProcessor {
  concurrency?: number;
  name?: string;
  processorPath: BullQueueSeparateProcessor;
}
```

@iveselin @cgarnier What do you think of this? Would this implementation bring an answer to your needs?

**Comment by iveselin** [comment]
@fwoelffel 
Looks like an ok solution, little bit of confusion is when you use just a e.g. fuction name its executed in same process, but when you use a path to the file with the same function its executed as separate process... maybe add optional param in interface, something like separateProcess boolean?

Also, I see its a fork process, are services/repos accesable from that fork?

**Comment by fwoelffel** [comment]
As you've seen in Bull [docs](https://github.com/OptimalBits/bull#separate-processes), passing a filesystem path is the way to handle jobs in a separate process. Moreover, that's the only way to start a fork. Given that the job processor lives in another process, you can't benefit from Nestjs' dependency injection, as said in my first answer.

If you want to handle jobs in separate processes and use services/repos, I suggest you to have a look at [Node.js' clusterss](https://nodejs.org/api/cluster.html#cluster_cluster).

**Comment by fwoelffel** [comment]
@iveselin @cgarnier feel free to review #74 

I still have some to refactor some functions and add tests but the feature is implemented and working. Today is a day off, I'll try to merge before the end of this week.

**Comment by cgarnier** [comment]
I think we should not have to think about how are run the job in the app. I think it nice to have the possibility to start a number of workers process and let them pick the jobs. Maybe just some config to enable/disable the job execution by the main process and know who is a worker or not.
We can manage to start processes with cluster or pm2.

**Comment by cgarnier** [comment]
@fwoelffel is it possible to use the services in the pr example  ?

**Comment by fwoelffel** [comment]
Maybe I'm misunderstanding what you mean but as I stated, services and any other components won't be available since the processor function will be running in a separate process. If you have an idea on how to get access to the Nest app components, you can provide a example or some instructions.

**Comment by fjur** [comment]
@fwoelffel Implemented a similar solution to @cgarnier, have two modules, one for the app and one for the worker. The app puts events onto the queue, and the worker process them. Noticing that because the app has a bull queue to add events onto the queue, the queue will try and make the app process invents instead of solely the workers. This fails with `Missing process handler for job type <job name>`. This happens roughly 50% of the time with 1 app process and 1 worker process

Confirmed this is the issue by adding a repeatable event onto the queue and then shutting down the app process, the events succeed without failing in this case.

How do you make it so the app can add events onto the queue, but the queue won't try and use the app for processing events and only use the workers?

**Comment by w8ze-devel** [comment]
Hello,

I've juste tried experimenting separed process but encounter a lot of problems.

Here is the module configuration :

```
    BullModule.registerQueue({
      name: 'audio',
      processors: [{
        name: 'audio-handler',
        path: join(__dirname, 'processor.js')}
      ]
    })
```

Here is the code : (file processor.ts)


```
import { Job, DoneCallback } from 'bull';

async function imageProcessor(job: Job, doneCallback: DoneCallback) {
    console.log(`In imageProcessor -> [${process.pid}] ${JSON.stringify(job.id)}`);

    doneCallback(null, "It works");
}

export default imageProcessor;
```

In Redis, i always have an error meaning that the job cannot be processed

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/93590948/210255555-63ed2477-3995-4ebb-b6a2-341fbe60be83.png">

Any idea please ?

Thanks
